cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

set(ANTIPRISM_VERSION "1.0")
set(ANTIPRISM_LANGUAGES )
set(ANTIPRISM_CODESIGNING )
set(SW_VERS "")
set(UNAME_M "")

if (APPLE)
    list(APPEND ANTIPRISM_LANGUAGES "C")
    list(APPEND ANTIPRISM_LANGUAGES "CXX")
    list(APPEND ANTIPRISM_LANGUAGES "OBJC")
    list(APPEND ANTIPRISM_LANGUAGES "OBJCXX")
    execute_process(COMMAND sw_vers -productVersion OUTPUT_VARIABLE SW_VERS ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if ("${CMAKE_GENERATOR}" MATCHES "Xcode")
        execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if (NOT "$ENV{SYSROOT}" STREQUAL "")
            set(SYSROOT "$ENV{SYSROOT}")
        else()
            execute_process(COMMAND xcodebuild -version -sdk macosx Path OUTPUT_VARIABLE SYSROOT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if (NOT EXISTS "${SYSROOT}")
            message(FATAL_ERROR "SYSROOT does not exist!")
        endif()
        set(CMAKE_OSX_SYSROOT "${SYSROOT}" CACHE STRING "CMAKE_OSX_SYSROOT" FORCE)
        if ("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            if ("${UNAME_M}" MATCHES "arm")
                set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            else()
                set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            endif()
        endif()
    endif()
    execute_process(COMMAND security find-identity -v -p codesigning OUTPUT_VARIABLE SECURITY_FOUND_IDENTITY ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PATTERN " ")
    foreach (IDX RANGE 1 40 1)
        string(APPEND PATTERN "[a-fA-F0-9]")
    endforeach()
    string(APPEND PATTERN " ")
    string(REGEX MATCH "${PATTERN}" IDENTITY "${SECURITY_FOUND_IDENTITY}")
    if (NOT "${IDENTITY}" STREQUAL "")
        string(STRIP "${IDENTITY}" ANTIPRISM_CODESIGNING)
    endif()
else()
    list(APPEND ANTIPRISM_LANGUAGES "C")
    list(APPEND ANTIPRISM_LANGUAGES "CXX")
    if (MINGW)
        list(APPEND ANTIPRISM_LANGUAGES "RC")
    endif()
endif()

macro(set_option var default type docstring)
	  if (("${type}" STREQUAL "STRING" AND "${var}" STREQUAL "") OR NOT DEFINED ${var})
		    set(${var} ${default})
	  endif()
	  set(${var} ${${var}} CACHE ${type} ${docstring} FORCE)
endmacro()

if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND NOT "${SW_VERS}" STREQUAL "")
    string(REPLACE "." ";" SW_VERS_MAJOR "${SW_VERS}")
    list(POP_FRONT SW_VERS_MAJOR SW_VERS_HEAD)
    set(SW_VERS "${SW_VERS_HEAD}")
    set_option(CMAKE_OSX_DEPLOYMENT_TARGET "${SW_VERS}" STRING "Choose the minimum MacOS deployment version")
endif()
set_option(CMAKE_BUILD_TYPE "Debug" STRING "Choose the type of build config variant (\"Debug\" or \"Release\")")
set_option(ANTIPRISM_LINKAGE "STATIC" STRING "Choose the type of library linkage for the libantiprism target (\"STATIC\" or \"SHARED\")")
set_option(ANTIPRISM_BINARIES "ON" STRING "Whether or not to build the antiprism executable targets (\"ON\" or \"OFF\")")
set_option(ANTIPRISM_VIEWER "ON" STRING "Whether or not to build the antiview executable target (\"ON\" or \"OFF\")")
set_option(ANTIPRISM_TESTING "OFF" STRING "Whether or not to run unit tests (\"ON\" or \"OFF\")")

project(antiprism VERSION ${ANTIPRISM_VERSION} LANGUAGES ${ANTIPRISM_LANGUAGES})

set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "")
if (NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    set(CMAKE_DEBUG_POSTFIX "${CMAKE_BUILD_TYPE}")
endif()

set(ANTIPRISM_DEF )
list(APPEND ANTIPRISM_DEF VERSION="${ANTIPRISM_VERSION}")
list(APPEND ANTIPRISM_DEF MUP_CMAKE)
list(APPEND ANTIPRISM_DEF ANTIPRISM_CMAKE)
if ("${ANTIPRISM_LINKAGE}" STREQUAL "SHARED")
    list(APPEND ANTIPRISM_DEF ANTIPRISM_LIBRARY_TYPE_SHARED)
else()
    list(APPEND ANTIPRISM_DEF ANTIPRISM_LIBRARY_TYPE_STATIC)
endif()
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    list(APPEND ANTIPRISM_DEF ANTIPRISM_DEBUG)
endif()
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    list(APPEND ANTIPRISM_DEF ANTIPRISM_CLANG)
endif()
if (APPLE)
    list(APPEND ANTIPRISM_DEF ANTIPRISM_OS_APPLE)
elseif (ANDROID)
    list(APPEND ANTIPRISM_DEF ANTIPRISM_OS_ANDROID)
elseif (MINGW OR MSVC)
    list(APPEND ANTIPRISM_DEF ANTIPRISM_OS_WINDOWS)
    if (MINGW)
        list(APPEND ANTIPRISM_DEF ANTIPRISM_MINGW)
    endif()
else()
    list(APPEND ANTIPRISM_DEF ANTIPRISM_OS_LINUX)
endif()
if ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
    list(APPEND ANTIPRISM_DEF ANTIPRISM_BITNESS_32)
else ()
    list(APPEND ANTIPRISM_DEF ANTIPRISM_BITNESS_64)
endif ()
include(TestBigEndian)
TEST_BIG_ENDIAN(IS_BIG_ENDIAN)
if (IS_BIG_ENDIAN)
    list(APPEND ANTIPRISM_DEF ANTIPRISM_ENDIANNESS_BIG)
else()
    list(APPEND ANTIPRISM_DEF ANTIPRISM_ENDIANNESS_LITTLE)
endif()
if ("${CMAKE_INSTALL_PREFIX}" STREQUAL "")
    list(APPEND ANTIPRISM_DEF SUPDIR="${CMAKE_CURRENT_LIST_DIR}/share")
else()
    if (IS_ABSOLUTE "${CMAKE_INSTALL_PREFIX}")
        list(APPEND ANTIPRISM_DEF SUPDIR="${CMAKE_INSTALL_PREFIX}/share/antiprism")
    else()
        get_filename_component(ANTIPRISM_SHARE "${CMAKE_INSTALL_PREFIX}" REALPATH BASE_DIR "${CMAKE_CURRENT_LIST_DIR}")
        list(APPEND ANTIPRISM_DEF SUPDIR="${ANTIPRISM_SHARE}/share/antiprism")
    endif()
endif()
if (WINDOWS)
    list(APPEND ANTIPRISM_DEF USLEEP=2)
    list(APPEND ANTIPRISM_DEF UTIMER=2)
else()
    list(APPEND ANTIPRISM_DEF USLEEP=1)
    list(APPEND ANTIPRISM_DEF UTIMER=1)
endif()

include_directories(${CMAKE_CURRENT_LIST_DIR}/base)
include_directories(${CMAKE_CURRENT_LIST_DIR}/base/qhull)
include_directories(${CMAKE_CURRENT_LIST_DIR}/base/tesselator)
include_directories(${CMAKE_CURRENT_LIST_DIR}/base/muparser)

set(ANTIPRISM_LIB_DEF )
foreach (DEF IN LISTS ANTIPRISM_DEF)
    list(APPEND ANTIPRISM_LIB_DEF ${DEF})
endforeach()
list(APPEND ANTIPRISM_LIB_DEF ANTIPRISM_TARGET_TYPE_LIBRARY)

set(ANTIPRISM_LIB_SRC )
set(ANTIPRISM_LIB_INC )

list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/off_read.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/off_write.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/crds_read.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/displaypoly.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/geometry.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/geometryutils.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/colormap.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/color.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/dual.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/programopts.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/status.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vec3d.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/trans3d.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vec4d.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/trans4d.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vec_utils.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vec_utils_norm.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vec_utils_cent.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/utils.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/utils_parser.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/getopt.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/mathutils.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/normal.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/c_hull.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/triangulate.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/iteration.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/symmetry.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/sort_merge.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/boundbox.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/geometryinfo.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/coloring.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/prop_col.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/named_cols.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/geodesic.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/zonohedron.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/johnson.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/uniform.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/std_polys.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/skilling.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/stellations.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/timer.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/polygon.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/povwriter.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/scene.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/canonical.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/trans.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/faces.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/vrmlwriter.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/wythoff.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/wythoff_tiling.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/wythoff_ops.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/planar.cc)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/antiprism.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/boundbox.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/elemprops.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/colormap.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/coloring.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/color.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/const.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/displaypoly.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/geometry.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/geometryutils.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/geometryinfo.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/iteration.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/trans3d.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/trans4d.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/mathutils.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/normal.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/polygon.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/povwriter.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/programopts.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/random.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/scene.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/status.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/symmetry.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tiling.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/timer.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/utils.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/getopt.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/vec3d.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/vec4d.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/vec_utils.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/vrmlwriter.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/planar.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_geodesic.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_misc.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_named_cols.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_off_file.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_prop_col.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/private_std_polys.h)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/geom2_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/geom_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/global_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/io_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/libqhull_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/mem_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/merge_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/poly2_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/poly_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/qset_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/random_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/rboxlib_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/stat_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/usermem_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/userprintf_rbox_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/userprintf_r.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/user_r.cc)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/geom_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/io_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/libqhull_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/mem_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/merge_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/poly_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/qhull_ra.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/qset_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/random_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/stat_r.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/qhull/user_r.h)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/dict.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/geom.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/memalloc.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/mesh.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/normal.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/priorityq.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/render.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/sweep.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/tess.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/tessmono.cc)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/priorityq-heap_c.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/dict.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/dict-list.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/geom.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/gl.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/glu.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/gluos.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/memalloc.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/mesh.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/normal.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/priorityq.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/priorityq-heap.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/priorityq-sort.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/render.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/sweep.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/tess.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/tesselator/tessmono.h)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserBase.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserBytecode.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserCallback.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParser.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserDLL.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserError.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserInt.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserTest.cc)
list(APPEND ANTIPRISM_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserTokenReader.cc)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserBase.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserBytecode.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserCallback.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserDef.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserDLL.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserError.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserFixes.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParser.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserInt.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserStack.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserTemplateMagic.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserTest.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserToken.h)
list(APPEND ANTIPRISM_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/base/muparser/muParserTokenReader.h)
foreach (INC IN LISTS ANTIPRISM_LIB_INC)
    list(APPEND ANTIPRISM_LIB_SRC ${INC})
endforeach()

add_library(libantiprism ${ANTIPRISM_LINKAGE} ${ANTIPRISM_LIB_SRC})
if ("${ANTIPRISM_LINKAGE}" STREQUAL "SHARED" AND (APPLE OR WINDOWS))
    install(TARGETS libantiprism RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/bin FRAMEWORK DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
else()
    install(TARGETS libantiprism)
endif()
target_compile_features(libantiprism PRIVATE cxx_std_17)
set_target_properties(libantiprism PROPERTIES LINKER_LANGUAGE CXX)
target_compile_definitions(libantiprism PRIVATE ${ANTIPRISM_LIB_DEF})
#set_target_properties(libantiprism PROPERTIES PUBLIC_HEADER "${ANTIPRISM_LIB_INC}")
file(GLOB ANTIPRISM_SHARES ${CMAKE_CURRENT_LIST_DIR}/share/**/*)
if (NOT "${CMAKE_INSTALL_PREFIX}" STREQUAL "")
    foreach (SHARES IN LISTS ANTIPRISM_SHARES)
        if (NOT IS_DIRECTORY ${SHARES})
            file(RELATIVE_PATH SHARE ${CMAKE_CURRENT_LIST_DIR}/share ${SHARES})
            get_filename_component(ANTIPRISM_SHARES "${SHARE}" DIRECTORY)
            install(FILES ${SHARES} DESTINATION ${CMAKE_INSTALL_PREFIX}/share/${ANTIPRISM_SHARES})
        endif()
    endforeach()
    install(FILES ${ANTIPRISM_LIB_INC} DESTINATION ${CMAKE_INSTALL_PREFIX}/include)
endif()

set(ANTIPRISM_BIN_DEF )
foreach (DEF IN LISTS ANTIPRISM_DEF)
    list(APPEND ANTIPRISM_BIN_DEF ${DEF})
endforeach()
list(APPEND ANTIPRISM_BIN_DEF ANTIPRISM_TARGET_TYPE_EXECUTABLE)
if ("${ANTIPRISM_VIEWER}" STREQUAL "ON")
    list(APPEND ANTIPRISM_BIN_DEF HAVE_GLUT_H)
endif()

set(ANTIPRISM_BIN_SRC_OFF2POV )
list(APPEND ANTIPRISM_BIN_SRC_OFF2POV ${CMAKE_CURRENT_LIST_DIR}/src/off2pov.cc)

set(ANTIPRISM_BIN_SRC_OFF2CRDS )
list(APPEND ANTIPRISM_BIN_SRC_OFF2CRDS ${CMAKE_CURRENT_LIST_DIR}/src/off2crds.cc)

set(ANTIPRISM_BIN_SRC_OFF2OBJ )
list(APPEND ANTIPRISM_BIN_SRC_OFF2OBJ ${CMAKE_CURRENT_LIST_DIR}/src/off2obj.cc)

set(ANTIPRISM_BIN_SRC_OBJ2OFF )
list(APPEND ANTIPRISM_BIN_SRC_OBJ2OFF ${CMAKE_CURRENT_LIST_DIR}/src/obj2off.cc)
list(APPEND ANTIPRISM_BIN_SRC_OBJ2OFF ${CMAKE_CURRENT_LIST_DIR}/src/tiny_obj_loader.h)

set(ANTIPRISM_BIN_SRC_OFF2VRML )
list(APPEND ANTIPRISM_BIN_SRC_OFF2VRML ${CMAKE_CURRENT_LIST_DIR}/src/off2vrml.cc)

set(ANTIPRISM_BIN_SRC_OFF2DAE )
list(APPEND ANTIPRISM_BIN_SRC_OFF2DAE ${CMAKE_CURRENT_LIST_DIR}/src/off2dae.cc)

set(ANTIPRISM_BIN_SRC_OFF_COLOR )
list(APPEND ANTIPRISM_BIN_SRC_OFF_COLOR ${CMAKE_CURRENT_LIST_DIR}/src/off_color.cc)

set(ANTIPRISM_BIN_SRC_OFF_COLOR_RADIAL )
list(APPEND ANTIPRISM_BIN_SRC_OFF_COLOR_RADIAL ${CMAKE_CURRENT_LIST_DIR}/src/off_color_radial.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_COLOR_RADIAL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_COLOR_RADIAL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_OFF_UTIL )
list(APPEND ANTIPRISM_BIN_SRC_OFF_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/off_util.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/help.h)

set(ANTIPRISM_BIN_SRC_OFF_TRANS )
list(APPEND ANTIPRISM_BIN_SRC_OFF_TRANS ${CMAKE_CURRENT_LIST_DIR}/src/off_trans.cc)

set(ANTIPRISM_BIN_SRC_OFF_ALIGN )
list(APPEND ANTIPRISM_BIN_SRC_OFF_ALIGN ${CMAKE_CURRENT_LIST_DIR}/src/off_align.cc)

set(ANTIPRISM_BIN_SRC_PLANAR )
list(APPEND ANTIPRISM_BIN_SRC_PLANAR ${CMAKE_CURRENT_LIST_DIR}/src/planar.cc)
list(APPEND ANTIPRISM_BIN_SRC_PLANAR ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_PLANAR ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_OFF_REPORT )
list(APPEND ANTIPRISM_BIN_SRC_OFF_REPORT ${CMAKE_CURRENT_LIST_DIR}/src/off_report.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_REPORT ${CMAKE_CURRENT_LIST_DIR}/src/rep_print.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_REPORT ${CMAKE_CURRENT_LIST_DIR}/src/rep_print.h)

set(ANTIPRISM_BIN_SRC_OFF_QUERY )
list(APPEND ANTIPRISM_BIN_SRC_OFF_QUERY ${CMAKE_CURRENT_LIST_DIR}/src/off_query.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_QUERY ${CMAKE_CURRENT_LIST_DIR}/src/rep_print.cc)
list(APPEND ANTIPRISM_BIN_SRC_OFF_QUERY ${CMAKE_CURRENT_LIST_DIR}/src/rep_print.h)

set(ANTIPRISM_BIN_SRC_OFF_NORMALS )
list(APPEND ANTIPRISM_BIN_SRC_OFF_NORMALS ${CMAKE_CURRENT_LIST_DIR}/src/off_normals.cc)

set(ANTIPRISM_BIN_SRC_CONV_HULL )
list(APPEND ANTIPRISM_BIN_SRC_CONV_HULL ${CMAKE_CURRENT_LIST_DIR}/src/conv_hull.cc)

set(ANTIPRISM_BIN_SRC_POL_RECIP )
list(APPEND ANTIPRISM_BIN_SRC_POL_RECIP ${CMAKE_CURRENT_LIST_DIR}/src/pol_recip.cc)

set(ANTIPRISM_BIN_SRC_CANONICAL )
list(APPEND ANTIPRISM_BIN_SRC_CANONICAL ${CMAKE_CURRENT_LIST_DIR}/src/canonical.cc)
list(APPEND ANTIPRISM_BIN_SRC_CANONICAL ${CMAKE_CURRENT_LIST_DIR}/src/canonical_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_CANONICAL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_CANONICAL ${CMAKE_CURRENT_LIST_DIR}/src/canonical_common.h)
list(APPEND ANTIPRISM_BIN_SRC_CANONICAL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_GEODESIC )
list(APPEND ANTIPRISM_BIN_SRC_GEODESIC ${CMAKE_CURRENT_LIST_DIR}/src/geodesic.cc)

set(ANTIPRISM_BIN_SRC_ZONO )
list(APPEND ANTIPRISM_BIN_SRC_ZONO ${CMAKE_CURRENT_LIST_DIR}/src/zono.cc)

set(ANTIPRISM_BIN_SRC_STELLATE )
list(APPEND ANTIPRISM_BIN_SRC_STELLATE ${CMAKE_CURRENT_LIST_DIR}/src/stellate.cc)
list(APPEND ANTIPRISM_BIN_SRC_STELLATE ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_STELLATE ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_CONWAY )
list(APPEND ANTIPRISM_BIN_SRC_CONWAY ${CMAKE_CURRENT_LIST_DIR}/src/conway.cc)
list(APPEND ANTIPRISM_BIN_SRC_CONWAY ${CMAKE_CURRENT_LIST_DIR}/src/canonical_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_CONWAY ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_CONWAY ${CMAKE_CURRENT_LIST_DIR}/src/canonical_common.h)
list(APPEND ANTIPRISM_BIN_SRC_CONWAY ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_WYTHOFF )
list(APPEND ANTIPRISM_BIN_SRC_WYTHOFF ${CMAKE_CURRENT_LIST_DIR}/src/wythoff.cc)

set(ANTIPRISM_BIN_SRC_POLY_KSCOPE )
list(APPEND ANTIPRISM_BIN_SRC_POLY_KSCOPE ${CMAKE_CURRENT_LIST_DIR}/src/poly_kscope.cc)

set(ANTIPRISM_BIN_SRC_TO_NFOLD )
list(APPEND ANTIPRISM_BIN_SRC_TO_NFOLD ${CMAKE_CURRENT_LIST_DIR}/src/to_nfold.cc)

set(ANTIPRISM_BIN_SRC_SYMMETRO )
list(APPEND ANTIPRISM_BIN_SRC_SYMMETRO ${CMAKE_CURRENT_LIST_DIR}/src/symmetro.cc)
list(APPEND ANTIPRISM_BIN_SRC_SYMMETRO ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_SYMMETRO ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_KCYCLE )
list(APPEND ANTIPRISM_BIN_SRC_KCYCLE ${CMAKE_CURRENT_LIST_DIR}/src/kcycle.cc)

set(ANTIPRISM_BIN_SRC_LEONARDO )
list(APPEND ANTIPRISM_BIN_SRC_LEONARDO ${CMAKE_CURRENT_LIST_DIR}/src/leonardo.cc)

set(ANTIPRISM_BIN_SRC_POLY_FORM )
list(APPEND ANTIPRISM_BIN_SRC_POLY_FORM ${CMAKE_CURRENT_LIST_DIR}/src/poly_form.cc)

set(ANTIPRISM_BIN_SRC_COL_UTIL )
list(APPEND ANTIPRISM_BIN_SRC_COL_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/col_util.cc)

set(ANTIPRISM_BIN_SRC_LAT_UTIL )
list(APPEND ANTIPRISM_BIN_SRC_LAT_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/lat_util.cc)
list(APPEND ANTIPRISM_BIN_SRC_LAT_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_LAT_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_LAT_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.h)
list(APPEND ANTIPRISM_BIN_SRC_LAT_UTIL ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_POLYGON )
list(APPEND ANTIPRISM_BIN_SRC_POLYGON ${CMAKE_CURRENT_LIST_DIR}/src/polygon.cc)

set(ANTIPRISM_BIN_SRC_MILLER )
list(APPEND ANTIPRISM_BIN_SRC_MILLER ${CMAKE_CURRENT_LIST_DIR}/src/miller.cc)
list(APPEND ANTIPRISM_BIN_SRC_MILLER ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_MILLER ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_TETRA59 )
list(APPEND ANTIPRISM_BIN_SRC_TETRA59 ${CMAKE_CURRENT_LIST_DIR}/src/tetra59.cc)
list(APPEND ANTIPRISM_BIN_SRC_TETRA59 ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_TETRA59 ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_ISO_DELTA )
list(APPEND ANTIPRISM_BIN_SRC_ISO_DELTA ${CMAKE_CURRENT_LIST_DIR}/src/iso_delta.cc)
list(APPEND ANTIPRISM_BIN_SRC_ISO_DELTA ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_ISO_DELTA ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_ISO_KITE )
list(APPEND ANTIPRISM_BIN_SRC_ISO_KITE ${CMAKE_CURRENT_LIST_DIR}/src/iso_kite.cc)

set(ANTIPRISM_BIN_SRC_UNITILE2D )
list(APPEND ANTIPRISM_BIN_SRC_UNITILE2D ${CMAKE_CURRENT_LIST_DIR}/src/unitile2d.cc)

set(ANTIPRISM_BIN_SRC_N_ICONS )
list(APPEND ANTIPRISM_BIN_SRC_N_ICONS ${CMAKE_CURRENT_LIST_DIR}/src/n_icons.cc)
list(APPEND ANTIPRISM_BIN_SRC_N_ICONS ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_N_ICONS ${CMAKE_CURRENT_LIST_DIR}/src/n_icons.h)
list(APPEND ANTIPRISM_BIN_SRC_N_ICONS ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_WATERMAN )
list(APPEND ANTIPRISM_BIN_SRC_WATERMAN ${CMAKE_CURRENT_LIST_DIR}/src/waterman.cc)
list(APPEND ANTIPRISM_BIN_SRC_WATERMAN ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_WATERMAN ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_WATERMAN ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.h)
list(APPEND ANTIPRISM_BIN_SRC_WATERMAN ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_SPH_RINGS )
list(APPEND ANTIPRISM_BIN_SRC_SPH_RINGS ${CMAKE_CURRENT_LIST_DIR}/src/sph_rings.cc)

set(ANTIPRISM_BIN_SRC_REPEL )
list(APPEND ANTIPRISM_BIN_SRC_REPEL ${CMAKE_CURRENT_LIST_DIR}/src/repel.cc)

set(ANTIPRISM_BIN_SRC_BRAVAIS )
list(APPEND ANTIPRISM_BIN_SRC_BRAVAIS ${CMAKE_CURRENT_LIST_DIR}/src/bravais.cc)
list(APPEND ANTIPRISM_BIN_SRC_BRAVAIS ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_BRAVAIS ${CMAKE_CURRENT_LIST_DIR}/src/color_common.cc)
list(APPEND ANTIPRISM_BIN_SRC_BRAVAIS ${CMAKE_CURRENT_LIST_DIR}/src/lat_util_common.h)
list(APPEND ANTIPRISM_BIN_SRC_BRAVAIS ${CMAKE_CURRENT_LIST_DIR}/src/color_common.h)

set(ANTIPRISM_BIN_SRC_SPIDRON )
list(APPEND ANTIPRISM_BIN_SRC_SPIDRON ${CMAKE_CURRENT_LIST_DIR}/src_extra/spidron.cc)

set(ANTIPRISM_BIN_SRC_DOME_LAYER )
list(APPEND ANTIPRISM_BIN_SRC_DOME_LAYER ${CMAKE_CURRENT_LIST_DIR}/src_extra/dome_layer.cc)

set(ANTIPRISM_BIN_SRC_POLY_WEAVE )
list(APPEND ANTIPRISM_BIN_SRC_POLY_WEAVE ${CMAKE_CURRENT_LIST_DIR}/src_extra/poly_weave.cc)

set(ANTIPRISM_BIN_SRC_MMOP_ORIGAMI )
list(APPEND ANTIPRISM_BIN_SRC_MMOP_ORIGAMI ${CMAKE_CURRENT_LIST_DIR}/src_extra/mmop_origami.cc)

set(ANTIPRISM_BIN_SRC_JITTERBUG )
list(APPEND ANTIPRISM_BIN_SRC_JITTERBUG ${CMAKE_CURRENT_LIST_DIR}/src_extra/jitterbug.cc)

set(ANTIPRISM_BIN_SRC_STRING_ART )
list(APPEND ANTIPRISM_BIN_SRC_STRING_ART ${CMAKE_CURRENT_LIST_DIR}/src_extra/string_art.cc)

set(ANTIPRISM_BIN_SRC_ROTEGRITY )
list(APPEND ANTIPRISM_BIN_SRC_ROTEGRITY ${CMAKE_CURRENT_LIST_DIR}/src_extra/rotegrity.cc)

set(ANTIPRISM_BIN_SRC_SWEEP_EDGES )
list(APPEND ANTIPRISM_BIN_SRC_SWEEP_EDGES ${CMAKE_CURRENT_LIST_DIR}/src_extra/sweep_edges.cc)

set(ANTIPRISM_BIN_SRC_LAT_GRID )
list(APPEND ANTIPRISM_BIN_SRC_LAT_GRID ${CMAKE_CURRENT_LIST_DIR}/src_extra/lat_grid.cc)

if ("${ANTIPRISM_BINARIES}" STREQUAL "ON")
    set(FIRST )
    set(ANTIPRISM_BIN )
    if ("${ANTIPRISM_VIEWER}" STREQUAL "ON")
        find_package(OpenGL REQUIRED)
        find_package(GLUT REQUIRED)
        set(ANTIPRISM_BIN_SRC )
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/gl_writer.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/stipple.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/gl_stroke_font.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/displaypoly_gl.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/antiview.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/vw_glut.cc)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/gl_stroke_font.h)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/gl_writer.h)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/displaypoly_gl.h)
        list(APPEND ANTIPRISM_BIN_SRC ${CMAKE_CURRENT_LIST_DIR}/aview/vw_glut.h)
        add_executable(antiview ${ANTIPRISM_BIN_SRC})
        list(APPEND ANTIPRISM_BIN antiview)
        if ("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows")
            target_include_directories(antiview PRIVATE ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/aview ${CMAKE_CURRENT_LIST_DIR}/base ${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIR}/GL)
            target_link_libraries(antiview ${OPENGL_LIBRARIES} GLUT::GLUT libantiprism)
            #add_custom_command(TARGET antiview POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:GLUT::GLUT> ${CMAKE_INSTALL_PREFIX}/bin)
        else()
            target_include_directories(antiview PRIVATE ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_CURRENT_LIST_DIR}/aview ${CMAKE_CURRENT_LIST_DIR}/base ${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIR})
            if (APPLE)
                target_link_libraries(antiview ${OPENGL_LIBRARIES} ${GLUT_glut_LIBRARY} ${GLUT_cocoa_LIBRARY} libantiprism)
            else()
                target_link_libraries(antiview ${OPENGL_LIBRARIES} ${GLUT_glut_LIBRARY} libantiprism)
            endif()
        endif()
    endif()
    add_executable(off2pov ${ANTIPRISM_BIN_SRC_OFF2POV})
    list(APPEND ANTIPRISM_BIN off2pov)
    add_executable(off2crds ${ANTIPRISM_BIN_SRC_OFF2CRDS})
    list(APPEND ANTIPRISM_BIN off2crds)
    add_executable(off2obj ${ANTIPRISM_BIN_SRC_OFF2OBJ})
    list(APPEND ANTIPRISM_BIN off2obj)
    add_executable(obj2off ${ANTIPRISM_BIN_SRC_OBJ2OFF})
    list(APPEND ANTIPRISM_BIN obj2off)
    add_executable(off2vrml ${ANTIPRISM_BIN_SRC_OFF2VRML})
    list(APPEND ANTIPRISM_BIN off2vrml)
    add_executable(off2dae ${ANTIPRISM_BIN_SRC_OFF2DAE})
    list(APPEND ANTIPRISM_BIN off2dae)
    add_executable(off_color ${ANTIPRISM_BIN_SRC_OFF_COLOR})
    list(APPEND ANTIPRISM_BIN off_color)
    add_executable(off_color_radial ${ANTIPRISM_BIN_SRC_OFF_COLOR_RADIAL})
    list(APPEND ANTIPRISM_BIN off_color_radial)
    add_executable(off_util ${ANTIPRISM_BIN_SRC_OFF_UTIL})
    list(APPEND ANTIPRISM_BIN off_util)
    add_executable(off_trans ${ANTIPRISM_BIN_SRC_OFF_TRANS})
    list(APPEND ANTIPRISM_BIN off_trans)
    add_executable(off_align ${ANTIPRISM_BIN_SRC_OFF_ALIGN})
    list(APPEND ANTIPRISM_BIN off_align)
    add_executable(planar ${ANTIPRISM_BIN_SRC_PLANAR})
    list(APPEND ANTIPRISM_BIN planar)
    add_executable(off_report ${ANTIPRISM_BIN_SRC_OFF_REPORT})
    list(APPEND ANTIPRISM_BIN off_report)
    add_executable(off_query ${ANTIPRISM_BIN_SRC_OFF_QUERY})
    list(APPEND ANTIPRISM_BIN off_query)
    add_executable(off_normals ${ANTIPRISM_BIN_SRC_OFF_NORMALS})
    list(APPEND ANTIPRISM_BIN off_normals)
    add_executable(conv_hull ${ANTIPRISM_BIN_SRC_CONV_HULL})
    list(APPEND ANTIPRISM_BIN conv_hull)
    add_executable(pol_recip ${ANTIPRISM_BIN_SRC_POL_RECIP})
    list(APPEND ANTIPRISM_BIN pol_recip)
    add_executable(canonical ${ANTIPRISM_BIN_SRC_CANONICAL})
    list(APPEND ANTIPRISM_BIN canonical)
    add_executable(geodesic ${ANTIPRISM_BIN_SRC_GEODESIC})
    list(APPEND ANTIPRISM_BIN geodesic)
    add_executable(zono ${ANTIPRISM_BIN_SRC_ZONO})
    list(APPEND ANTIPRISM_BIN zono)
    add_executable(stellate ${ANTIPRISM_BIN_SRC_STELLATE})
    list(APPEND ANTIPRISM_BIN stellate)
    add_executable(conway ${ANTIPRISM_BIN_SRC_CONWAY})
    list(APPEND ANTIPRISM_BIN conway)
    add_executable(wythoff ${ANTIPRISM_BIN_SRC_WYTHOFF})
    list(APPEND ANTIPRISM_BIN wythoff)
    add_executable(poly_kscope ${ANTIPRISM_BIN_SRC_POLY_KSCOPE})
    list(APPEND ANTIPRISM_BIN poly_kscope)
    add_executable(to_nfold ${ANTIPRISM_BIN_SRC_TO_NFOLD})
    list(APPEND ANTIPRISM_BIN to_nfold)
    add_executable(symmetro ${ANTIPRISM_BIN_SRC_SYMMETRO})
    list(APPEND ANTIPRISM_BIN symmetro)
    add_executable(kcycle ${ANTIPRISM_BIN_SRC_KCYCLE})
    list(APPEND ANTIPRISM_BIN kcycle)
    add_executable(leonardo ${ANTIPRISM_BIN_SRC_LEONARDO})
    list(APPEND ANTIPRISM_BIN leonardo)
    add_executable(poly_form ${ANTIPRISM_BIN_SRC_POLY_FORM})
    list(APPEND ANTIPRISM_BIN poly_form)
    add_executable(col_util ${ANTIPRISM_BIN_SRC_COL_UTIL})
    list(APPEND ANTIPRISM_BIN col_util)
    add_executable(lat_util ${ANTIPRISM_BIN_SRC_LAT_UTIL})
    list(APPEND ANTIPRISM_BIN lat_util)
    add_executable(polygon ${ANTIPRISM_BIN_SRC_POLYGON})
    list(APPEND ANTIPRISM_BIN polygon)
    add_executable(miller ${ANTIPRISM_BIN_SRC_MILLER})
    list(APPEND ANTIPRISM_BIN miller)
    add_executable(tetra59 ${ANTIPRISM_BIN_SRC_TETRA59})
    list(APPEND ANTIPRISM_BIN tetra59)
    add_executable(iso_delta ${ANTIPRISM_BIN_SRC_ISO_DELTA})
    list(APPEND ANTIPRISM_BIN iso_delta)
    add_executable(iso_kite ${ANTIPRISM_BIN_SRC_ISO_KITE})
    list(APPEND ANTIPRISM_BIN iso_kite)
    add_executable(unitile2d ${ANTIPRISM_BIN_SRC_UNITILE2D})
    list(APPEND ANTIPRISM_BIN unitile2d)
    add_executable(n_icons ${ANTIPRISM_BIN_SRC_N_ICONS})
    list(APPEND ANTIPRISM_BIN n_icons)
    add_executable(waterman ${ANTIPRISM_BIN_SRC_WATERMAN})
    list(APPEND ANTIPRISM_BIN waterman)
    add_executable(sph_rings ${ANTIPRISM_BIN_SRC_SPH_RINGS})
    list(APPEND ANTIPRISM_BIN sph_rings)
    add_executable(repel ${ANTIPRISM_BIN_SRC_REPEL})
    list(APPEND ANTIPRISM_BIN repel)
    add_executable(bravais ${ANTIPRISM_BIN_SRC_BRAVAIS})
    list(APPEND ANTIPRISM_BIN bravais)
    add_executable(spidron ${ANTIPRISM_BIN_SRC_SPIDRON})
    list(APPEND ANTIPRISM_BIN spidron)
    add_executable(dome_layer ${ANTIPRISM_BIN_SRC_DOME_LAYER})
    list(APPEND ANTIPRISM_BIN dome_layer)
    add_executable(poly_weave ${ANTIPRISM_BIN_SRC_POLY_WEAVE})
    list(APPEND ANTIPRISM_BIN poly_weave)
    add_executable(mmop_origami ${ANTIPRISM_BIN_SRC_MMOP_ORIGAMI})
    list(APPEND ANTIPRISM_BIN mmop_origami)
    add_executable(jitterbug ${ANTIPRISM_BIN_SRC_JITTERBUG})
    list(APPEND ANTIPRISM_BIN jitterbug)
    add_executable(string_art ${ANTIPRISM_BIN_SRC_STRING_ART})
    list(APPEND ANTIPRISM_BIN string_art)
    add_executable(rotegrity ${ANTIPRISM_BIN_SRC_ROTEGRITY})
    list(APPEND ANTIPRISM_BIN rotegrity)
    add_executable(sweep_edges ${ANTIPRISM_BIN_SRC_SWEEP_EDGES})
    list(APPEND ANTIPRISM_BIN sweep_edges)
    add_executable(lat_grid ${ANTIPRISM_BIN_SRC_LAT_GRID})
    list(APPEND ANTIPRISM_BIN lat_grid)
    foreach (BIN IN LISTS ANTIPRISM_BIN)
        add_dependencies(${BIN} libantiprism)
        install(TARGETS ${BIN} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin BUNDLE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
        target_compile_features(${BIN} PRIVATE cxx_std_17)
        set_target_properties(${BIN} PROPERTIES LINKER_LANGUAGE CXX)
        if (NOT "${BIN}" STREQUAL "antiview")
            target_link_libraries(${BIN} PRIVATE libantiprism)
        endif()
        target_compile_definitions(${BIN} PRIVATE ${ANTIPRISM_BIN_DEF})
        if (APPLE)
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/bin COMMENT "Make binary installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/lib COMMENT "Make library installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/include COMMENT "Make header installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT "${SW_VERS}" STREQUAL "")
                #set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development")
                #set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-")
                set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS ${CMAKE_CURRENT_LIST_DIR}/antiprism.entitlements)
                add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/antiprism.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:${BIN}> || :)
                if ("${ANTIPRISM_LINKAGE}" STREQUAL "SHARED" AND NOT "${FIRST}" STREQUAL " ")
                    add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/antiprism.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:libantiprism> || :)
                endif()
            endif()
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/" $<TARGET_FILE:${BIN}> || :)
            string(LENGTH "${ANTIPRISM_CODESIGNING}" LEN)
            if ("${LEN}" STREQUAL "40" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Release" AND NOT "${SW_VERS}" STREQUAL "")
                add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --sign "${ANTIPRISM_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:${BIN}> || :)
                if ("${ANTIPRISM_LINKAGE}" STREQUAL "SHARED" AND NOT "${FIRST}" STREQUAL " ")
                    add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --sign "${ANTIPRISM_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:libantiprism> || :)
                endif()
            endif()
        endif()
        set(FIRST " ")
    endforeach()
endif()

