const char *help_help =
"Help topics\n"
"===========\n"
"Type 'off_util -H topic_name' for help on each topic\n"
"\n"
"models: builtin models\n"
"   uniform: uniform polyhedra\n"
"   johnson: johnson polyhedra\n";


const char *help_models =
"Models\n"
"======\n"
"Antiprism includes a number of builtin models. These may be used\n"
"by any program that expects an OFF file, by passing the model name\n"
"instead of a file name e.g. antiview u1\n"
"\n"
"See the help topic for each model type for more details\n"
"   uniform: uniform polyhedra\n"
"   johnson: johnson polyhedra\n"
"   polygon: polygon-based polyhedra such as prisms, antiprisms,\n"
"            pyramids, dipyramids, cupolas, orthobicupolas, gyrobicupolas\n"
"            and snub-antiprisms\n";


const char *help_uniform =
"Uniform Polyhedra\n"
"=================\n"
"Uniform polyhdra can be specified by\n"
"\n"
"o   A U number e.g. u8\n"
"\n"
"o   u_ followed by a Wythoff Symbol e.g. \"u_2 4|3\"\n"
"\n"
"o   u_ followed by a name (see the list below) Use '_' instead of\n"
"    a space to avoid having to quote the model name. The beginning\n"
"    of a name can be given and the first match from the list of\n"
"    uniform polyhedra below is returned.\n"
"\n"
"    When giving a name the following abbreviations can be used\n"
"       tr:     truncated\n"
"       sm:     small\n"
"       gr:     great\n"
"       st:     stellated\n"
"       sn:     snub\n"
"       tet:    tetrahedron\n"
"       ico:    icosahedron\n"
"       icosa:  icosahedron\n"
"       dod:    dodecahedron\n"
"       oct:    octahedron\n"
"       cubo:   cuboctahedron\n"
"       icosid: icosidodecahedron\n"
"\n"
"    e.g. u_truncated_octahedron, u_tr_octahedron, u_tr_oct, u_tr_o\n"
"\n"
"o   Common polyhedra are given by name only\n"
"\n"
"     tet                    u1\n"
"     tetrahedron            u1\n"
"     tr_tetrahedron         u2\n"
"     tr_tet                 u2\n"
"     octahedron             u5\n"
"     oct                    u5\n"
"     cube                   u6\n"
"     cuboctahedron          u7\n"
"     cubo                   u7\n"
"     tr_octahedron          u8\n"
"     tr_oct                 u8\n"
"     tr_cube                u9\n"
"     rhombicuboctahedron    u10\n"
"     rhombicubo             u10\n"
"     tr_cuboctahedron       u11\n"
"     tr_cubo                u11\n"
"     snub_cube              u12\n"
"     icosahedron            u22\n"
"     ico                    u22\n"
"     icosa                  u22\n"
"     dodecahedron           u23\n"
"     dod                    u23\n"
"     icosidodecahedron      u24\n"
"     icosid                 u24\n"
"     tr_icosahedron         u25\n"
"     tr_ico                 u25\n"
"     tr_icosa               u25\n"
"     tr_dodecahedron        u26\n"
"     tr_dod                 u26\n"
"     rhombicosidodecahedron u27\n"
"     rhombicosid            u27\n"
"     tr_icosidodecahedron   u28\n"
"     tr_icosid              u28\n"
"     snub_dodecahedron      u29\n"
"     snub_dod               u29\n"
"\n"
"o    Uniform prism are named 'pri' followed by the polygon\n"
"     fraction e.g pri5, pri5/2\n"
"\n"
"o    Uniform antiprism are named 'ant' followed by the polygon\n"
"     fraction e.g ant5, ant5/2, ant5/3\n"
"\n"
"Uniform List:\n"
"\n"
"U No.  Wythoff Sym    Name\n"
"-----  -----------    ------------------------\n"
"U1           3|2 3    tetrahedron\n"
"U2           2 3|3    truncated tetrahedron\n"
"U3         3/2 3|3    octahemioctahedron\n"
"U4         3/2 3|2    tetrahemihexahedron\n"
"U5           4|2 3    octahedron\n"
"U6           3|2 4    cube\n"
"U7           2|3 4    cuboctahedron\n"
"U8           2 4|3    truncated octahedron\n"
"U9           2 3|4    truncated cube\n"
"U10          3 4|2    rhombicuboctahedron\n"
"U11         2 3 4|    truncated cuboctahedron\n"
"U12         |2 3 4    snub cube\n"
"U13        3/2 4|4    small cubicuboctahedron\n"
"U14        3 4|4/3    great cubicuboctahedron\n"
"U15        4/3 4|3    cubohemioctahedron\n"
"U16       4/3 3 4|    cubitruncated cuboctahedron\n"
"U17        3/2 4|2    great rhombicuboctahedron\n"
"U18       3/2 2 4|    small rhombihexahedron\n"
"U19        2 3|4/3    stellated truncated hexahedron\n"
"U20       4/3 2 3|    great truncated cuboctahedron\n"
"U21     4/3 3/2 2|    great rhombihexahedron\n"
"U22          5|2 3    icosahedron\n"
"U23          3|2 5    dodecahedron\n"
"U24          2|3 5    icosidodecahedron\n"
"U25          2 5|3    truncated icosahedron\n"
"U26          2 3|5    truncated dodecahedron\n"
"U27          3 5|2    rhombicosidodecahedron\n"
"U28         2 3 5|    truncated icosidodecahedron\n"
"U29         |2 3 5    snub dodecahedron\n"
"U30        3|5/2 3    small ditrigonal icosidodecahedron\n"
"U31        5/2 3|3    small icosicosidodecahedron\n"
"U32       |5/2 3 3    small snub icosicosidodecahedron\n"
"U33        3/2 5|5    small dodecicosidodecahedron\n"
"U34        5|2 5/2    small stellated dodecahedron\n"
"U35        5/2|2 5    great dodecahedron\n"
"U36        2|5/2 5    great dodecadodecahedron\n"
"U37        2 5/2|5    truncated great dodecahedron\n"
"U38        5/2 5|2    rhombidodecadodecahedron\n"
"U39       2 5/2 5|    small rhombidodecahedron\n"
"U40       |2 5/2 5    snub dodecadodecahedron\n"
"U41        3|5/3 5    ditrigonal dodecadodecahedron\n"
"U42        3 5|5/3    great ditrigonal dodecicosidodecahedron\n"
"U43        5/3 3|5    small ditrigonal dodecicosidodecahedron\n"
"U44        5/3 5|3    icosidodecadodecahedron\n"
"U45       5/3 3 5|    icositruncated dodecadodecahedron\n"
"U46       |5/3 3 5    snub icosidodecadodecahedron\n"
"U47        3/2|3 5    great ditrigonal icosidodecahedron\n"
"U48        3/2 5|3    great icosicosidodecahedron\n"
"U49        3/2 3|5    small icosihemidodecahedron\n"
"U50       3/2 3 5|    small dodecicosahedron\n"
"U51        5/4 5|5    small dodecahemidodecahedron\n"
"U52        3|2 5/2    great stellated dodecahedron\n"
"U53        5/2|2 3    great icosahedron\n"
"U54        2|5/2 3    great icosidodecahedron\n"
"U55        2 5/2|3    great truncated icosahedron\n"
"U56       2 5/2 3|    rhombicosahedron\n"
"U57       |2 5/2 3    great snub icosidodecahedron\n"
"U58        2 5|5/3    small stellated truncated dodecahedron\n"
"U59       5/3 2 5|    truncated dodecadodecahedron\n"
"U60       |5/3 2 5    inverted snub dodecadodecahedron\n"
"U61      5/2 3|5/3    great dodecicosidodecahedron\n"
"U62      5/3 5/2|3    small dodecahemicosahedron\n"
"U63     5/3 5/2 3|    great dodecicosahedron\n"
"U64     |5/3 5/2 3    great snub dodecicosidodecahedron\n"
"U65        5/4 5|3    great dodecahemicosahedron\n"
"U66        2 3|5/3    great stellated truncated dodecahedron\n"
"U67        5/3 3|2    great rhombicosidodecahedron\n"
"U68       5/3 2 3|    great truncated icosidodecahedron\n"
"U69       |5/3 2 3    great inverted snub icosidodecahedron\n"
"U70    5/3 5/2|5/3    great dodecahemidodecahedron\n"
"U71      3/2 3|5/3    great icosihemidodecahedron\n"
"U72   |3/2 3/2 5/2    small retrosnub icosicosidodecahedron\n"
"U73     3/2 5/3 2|    great rhombidodecahedron\n"
"U74     |3/2 5/3 2    great retrosnub icosidodecahedron\n"
"U75  3/2 5/3 3 5/2    great dirhombicosidodecahedron\n"
"U76          2 5|2    pentagonal prism\n"
"U77         |2 2 5    pentagonal antiprism\n"
"U78        2 5/2|2    pentagrammic prism\n"
"U79       |2 2 5/2    pentagrammic antiprism\n"
"U80       |2 2 5/3    pentagrammic crossed antiprism\n";


const char *help_johnson =
"Johnson Polyhedra\n"
"=================\n"
"Johnson polyhedra can be specified by a\n"
"\n"
"o   A J number e.g. j8\n"
"\n"
"o   j_ followed by a name (see the list below) Use '_' instead of\n"
"    a space to avoid having to quote the model name. The beginning\n"
"    of a name can be given and the first match from the list of\n"
"    Johnson polyhedra below is returned.\n"
"\n"
"    When giving a name the following abbreviations can be used\n"
"       tri:   triangular\n"
"       sq:    square\n"
"       squ:   square\n"
"       pe:    pentagonal\n"
"       pen:   pentagonal\n"
"       el:    elongated\n"
"       ge:    gyroelongated\n"
"       tr:    truncated\n"
"       au:    augmented\n"
"       ba:    biaugmenbted\n"
"       ta:    triaugmented\n"
"\n"
"    e.g. j_elongated_triangular_pyramid, j_el_tri_pyr, j_el\n"
"\n"
"\n"
"Johnson List:\n"
"\n"
"J No.  Name\n"
"-----  -------------------------------\n"
"\n"
"J1     square pyramid\n"
"J2     pentagonal pyramid\n"
"J3     triangular cupola\n"
"J4     square cupola\n"
"J5     pentagonal cupola\n"
"J6     pentagonal rotunda\n"
"J7     elongated triangular pyramid\n"
"J8     elongated square pyramid\n"
"J9     elongated pentagonal pyramid\n"
"J10    gyroelongated square pyramid\n"
"J11    gyroelongated pentagonal pyramid\n"
"J12    triangular dipyramid\n"
"J13    pentagonal dipyramid\n"
"J14    elongated triangular dipyramid\n"
"J15    elongated square dipyramid\n"
"J16    elongated pentagonal dipyramid\n"
"J17    gyroelongated square dipyramid\n"
"J18    elongated triangular cupola\n"
"J19    elongated square cupola\n"
"J20    elongated pentagonal cupola\n"
"J21    elongated pentagonal rotunda\n"
"J22    gyroelongated triangular cupola\n"
"J23    gyroelongated square cupola\n"
"J24    gyroelongated pentagonal cupola\n"
"J25    gyroelongated pentagonal rotunda\n"
"J26    gyrobifastigium\n"
"J27    triangular orthobicupola\n"
"J28    square orthobicupola\n"
"J29    square gyrobicupola\n"
"J30    pentagonal orthobicupola\n"
"J31    pentagonal gyrobicupola\n"
"J32    pentagonal orthocupolarotunda\n"
"J33    pentagonal gyrocupolarotunda\n"
"J34    pentagonal orthobirotunda\n"
"J35    elongated triangular orthobicupola\n"
"J36    elongated triangular gyrobicupola\n"
"J37    elongated square gyrobicupola\n"
"J38    elongated pentagonal orthobicupola\n"
"J39    elongated pentagonal gyrobicupola\n"
"J40    elongated pentagonal orthocupolarotunda\n"
"J41    elongated pentagonal gyrocupolarotunda\n"
"J42    elongated pentagonal orthobirotunda\n"
"J43    elongated pentagonal gyrobirotunda\n"
"J44    gyroelongated triangular bicupola\n"
"J45    gyroelongated square bicupola\n"
"J46    gyroelongated pentagonal bicupola\n"
"J47    gyroelongated pentagonal cupolarotunda\n"
"J48    gyroelongated pentagonal birotunda\n"
"J49    augmented triangular prism\n"
"J50    biaugmented triangular prism\n"
"J51    triaugmented triangular prism\n"
"J52    augmented pentagonal prism\n"
"J53    biaugmented pentagonal prism\n"
"J54    augmented hexagonal prism\n"
"J55    parabiaugmented hexagonal prism\n"
"J56    metabiaugmented hexagonal prism\n"
"J57    triaugmented hexagonal prism\n"
"J58    augmented dodecahedron\n"
"J59    parabiaugmented dodecahedron\n"
"J60    metabiaugmented dodecahedron\n"
"J61    triaugmented dodecahedron\n"
"J62    metabidiminished icosahedron\n"
"J63    tridiminished icosahedron\n"
"J64    augmented tridiminished icosahedron\n"
"J65    augmented truncated tetrahedron\n"
"J66    augmented truncated cube\n"
"J67    biaugmented truncated cube\n"
"J68    augmented truncated dodecahedron\n"
"J69    parabiaugmented truncated dodecahedron\n"
"J70    metabiaugmented truncated dodecahedron\n"
"J71    triaugmented truncated dodecahedron\n"
"J72    gyrate rhombicosidodecahedron\n"
"J73    parabigyrate rhombicosidodecahedron\n"
"J74    metabigyrate rhombicosidodecahedron\n"
"J75    trigyrate rhombicosidodecahedron\n"
"J76    diminished rhombicosidodecahedron\n"
"J77    paragyrate diminished rhombicosidodecahedron\n"
"J78    metagyrate diminished rhombicosidodecahedron\n"
"J79    bigyrate diminished rhombicosidodecahedron\n"
"J80    parabidiminished rhombicosidodecahedron\n"
"J81    metabidiminished rhombicosidodecahedron\n"
"J82    gyrate bidiminished rhombicosidodecahedron\n"
"J83    tridiminished rhombicosidodecahedron\n"
"J84    snub disphenoid\n"
"J85    snub square antiprism\n"
"J86    sphenocorona\n"
"J87    augmented sphenocorona\n"
"J88    sphenomegacorona\n"
"J89    hebesphenomegacorona\n"
"J90    disphenocingulum\n"
"J91    bilunabirotunda\n"
"J92    triangular hebesphenorotunda\n";


const char *help_polygon =
"Polygon-based Polyhedra\n"
"=======================\n"
"Polygon-based polyhedra have unit edges and are specified by their\n"
"abbreviated class name followed by the base polygon, given as a fraction.\n"
"(Note that some models, e.g. pyr7, cannot be made to have unit edges.)\n"
"\n"
"The class names are\n"
"   pri:     prism\n"
"   ant:     antiprism\n"
"   pyr:     pyramid\n"
"   dip:     dipyramid\n"
"   cup:     cupola\n"
"   ort:     orthobicupola\n"
"   gyr:     gyrobicupola\n"
"\n"
"   e.g. pri5, pyr7/2"
"\n";

